#!/usr/bin/env python

import sys.argv

if len(sys.argv) == 1:
    print "How frequently do you want to be reminded (in minutes)?"
    minutes = ""
    while type(minutes) == str:
        minutes = raw_input("Minutes: ")
        try:
            minutes = int(minutes)
        except ValueError:
            minutes = ""
else:
    minutes = int(sys.argv[1])

# Update the launchd script with this value
seconds = 60 * minutes

import nag
nag.create_launchd_script(seconds)

# Prettify the output
if minutes < 60:
    timestr = "%d minutes" % minutes
else:
    hours = minutes / 60
    minutes = minutes % 60
    if minutes == 0:
        timestr = "%d hours" % hours
    else:
        timestr = "%d hours %d minutes" % (hours, minutes)

print "We'll nag you every %s" % timestr
