#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    print "How frequently do you want to be reminded (in minutes)?"
    minutes = ""
    while type(minutes) == str:
        minutes = raw_input("Minutes: ")
        try:
            minutes = int(minutes)
        except ValueError:
            minutes = ""
else:
    minutes = int(sys.argv[1])

# Update the launchd script with this value
seconds = 60 * minutes

import nag
nag.create_launchd_script(seconds)

# Prettify the output
if minutes < 60:
    timestr = "%d minute%s" % (minutes, "" if minutes == 1 else "s")
else:
    hours = minutes / 60
    minutes = minutes % 60
    if minutes == 0:
        timestr = "%d hour%s" % (hours, "" if hours == 1 else "s")
    else:
        timestr = "%d hour%s %d minute%s" % (hours, "" if hours == 1 else "s", minutes, "" if minutes == 1 else "s")

print "We'll nag you every %s" % timestr
