#! /usr/bin/env python

import sys
import nag as nagutil
from dateutil.parser import parse
from datetime import datetime


def get_index(nags):
    index = ""
    while type(index) != int:
        index = raw_input("Index: ")
        try:
            index = int(index)
            # Out of bounds will go to IndexError below
            if nags[index][1] is not None:
                print "Nag %d has a time set; do you want to update it?" % index
                update = raw_input("y/N: ")
                if update in "yY":
                    continue
                else:
                    # Get a new index
                    index = ''
        except ValueError:
            pass
        except IndexError:
            print "No nag %d" % index
            index = ''
    return index

nags = nagutil.get_nags()

if len(sys.argv) < 2:
    print "Select nag to update:"
    for ind, nag in enumerate(nags):
        if nag[2]:
            continue
        print "(%d) %s" % (ind, nag[0])
    index = get_index(nags)
else:
    try:
        index = int(sys.argv[1])
    except IndexError:
        print "No nag %d" % index
        index = get_index(nags)

print "Do you want to complete this nag, or update the date?"
task = raw_input("c/U: ")

if task in "cC":
    print "Completing %s" % nags[index][0]
    nags[index][1] = datetime.now()
    nags[index][2] = True
else:
    print "When do you want to be nagged about '%s'?" % nags[index][0]
    dt = ""
    while type(dt) != datetime:
        dt = raw_input("")
        try:
            dt = parse(dt)
        except ValueError:
            print "Invalid date/time (%s)" % dt
    print "You'll be nagged about '%s' starting %s at %s" % (nags[index][0], "%02d/%02d/%d" % (dt.month, dt.day, dt.year), "%02d:%02d:%02d %s" % (dt.hour % 12 + 1, dt.minute, dt.second, "PM" if dt.hour / 12 else "AM"))
    nags[index][1] = dt

nagutil.save_nags(nags)
